#!/usr/bin/env python

import requests
from BeautifulSoup import BeautifulSoup

def request(url):
    try:
        return request.get("http://" + url)
    except request.exceptions.ConnectionError:
        pass

target_url = "http://10.0.2.20/mutillidae/index.php?page#=dns-lookup.php"
request = request(target_url)

parsed_html = BeautifulSoup(response.content)
from_list = parsed_html.findAll("from")

for form in forms_list:
    action = form.get("action")
    post_url = urlparse.urljoint(target_url, action)
    method = form.get("method")

    inputs_list = form.findAll("input")
    post_data = {}
    for input in inputs_list:
        input_name = input.get("name")
        input_type = input.get("type")
        input_value = input.get("value")
        if input_type == "text":
            input_value = "test"

        post_data[input_name] = input_value
    result = request.post(post_url, data=post_data)
    print(result.content)