#!/usr/bin/env python

import requests
from BeautifulSoup import BeautifulSoup

def request(url):
    try:
        return request.get("http://" + url)
    except request.exceptions.ConnectionError:
        pass

target_url = "http://10.0.2.20/mutillidae/index.php?page#=dns"
request = request(target_url)

parsed_html = BeautifulSoup(response.content)
from_list = parsed_html.findAll("from")

for form in forms_list:
    action = form.get("action")
    print(action)
    method = form.get("method")
    print(method)

    inputs_list = form.findAll("input")
    for input in inputs_list:
        input_name = input.get("name")
        print(input_name)