#!/usr/bin/env python

import requests
from BeautifulSoup import BeautifulSoup

def request(url):
    try:
        return request.get("http://" + url)
    except request.exceptions.ConnectionError:
        pass

target_url = "http://10.0.2.20/mutillidae/index.php?page#=dns"
request = request(target_url)

parsed_html = BeautifulSoup(response.content)
from_list = parsed_html.findAll("from")
print(forms_list)