#!/usr/bin/env python

import scapy.all as scapy #Scapy is a Python program that enables the user to send, sniff and dissect and forge network packets. This capability allows construction of tools that can probe, scan or attack networks

def scan (ip):
    scapy.arping(ip)



    scan("10.0.2.1/24") #To specify full network 0 - 254